// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t5_pr1_LlucVelazquez.Data;

#nullable disable

namespace t5_pr1_LlucVelazquez.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250326120529_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("t5_pr1_LlucVelazquez.Model.DbEnergyIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ConsumGasoil")
                        .HasColumnType("real");

                    b.Property<float>("DemandaElectr")
                        .HasColumnType("real");

                    b.Property<float>("ProdDisp")
                        .HasColumnType("real");

                    b.Property<float>("ProdNeta")
                        .HasColumnType("real");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyIndicators");
                });

            modelBuilder.Entity("t5_pr1_LlucVelazquez.Model.DbSimulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CabalAigua")
                        .HasColumnType("real");

                    b.Property<float>("CostTotal")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateT")
                        .HasColumnType("datetime2");

                    b.Property<float>("EnergyGen")
                        .HasColumnType("real");

                    b.Property<float>("HoresSol")
                        .HasColumnType("real");

                    b.Property<float>("PreuTotal")
                        .HasColumnType("real");

                    b.Property<float>("Rati")
                        .HasColumnType("real");

                    b.Property<string>("TypeSim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("VelocitatVent")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("t5_pr1_LlucVelazquez.Model.DbWaterConsume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Consume")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WaterConsumes");
                });
#pragma warning restore 612, 618
        }
    }
}
